import {useEffect,useMemo,useState} from "react";
import {LayoutDashboard,Users,Package,FileText,CreditCard,ArrowLeftRight,Receipt,BarChart3,Settings,LogOut,Menu,X,Plus,Search,Pencil,Trash2} from "lucide-react";
import {supabase} from "./lib/supabase";

const nav=[["dashboard","Dashboard",LayoutDashboard],["customers","Customers",Users],["products","Products",Package],["invoices","Invoices",FileText],["payments","Payments",CreditCard],["transactions","Transactions",ArrowLeftRight],["expenses","Expenses",Receipt],["reports","Reports",BarChart3],["settings","Settings",Settings]];
const blank={name:"",phone:"",email:"",address:"",city:"",state:"Rajasthan",pincode:"",gst_number:"",notes:""};

function Login(){const[e,setE]=useState(""),[p,setP]=useState(""),[err,setErr]=useState(""),[busy,setBusy]=useState(false);
async function go(x){x.preventDefault();setErr("");setBusy(true);const{error}=await supabase.auth.signInWithPassword({email:e,password:p});setBusy(false);if(error)setErr(error.message)}
return <main className="login"><div className="login-card"><div className="logo">NS</div><small>NEELKANTH STONES</small><h1>Business Management</h1><p>Billing, customers, payments and business records — all in one place.</p><form onSubmit={go}><label>Email</label><input type="email" value={e} onChange={x=>setE(x.target.value)} required/><label>Password</label><input type="password" value={p} onChange={x=>setP(x.target.value)} required/>{err&&<div className="error">{err}</div>}<button disabled={busy}>{busy?"Signing in...":"Sign in"}</button></form></div></main>}

function CustomerModal({item,onClose,onDone,businessId}){const[f,setF]=useState(item||blank),[err,setErr]=useState(""),[busy,setBusy]=useState(false);
const set=(k,v)=>setF(a=>({...a,[k]:v}));
async function save(e){e.preventDefault();if(!f.name.trim())return setErr("Customer name is required.");setBusy(true);const data={...f,name:f.name.trim(),business_id:businessId};let r=f.id?await supabase.from("customers").update(data).eq("id",f.id):await supabase.from("customers").insert(data);setBusy(false);if(r.error)setErr(r.error.message);else onDone()}
return <div className="modal-bg"><div className="modal"><div className="modal-top"><h2>{item?"Edit Customer":"Add Customer"}</h2><button className="icon" onClick={onClose}><X/></button></div><form className="grid" onSubmit={save}>{Object.keys(blank).map(k=><label className={["address","notes"].includes(k)?"wide":""} key={k}><span>{k.replace("_"," ")}</span>{k==="notes"?<textarea value={f[k]} onChange={e=>set(k,e.target.value)}/>:<input value={f[k]} onChange={e=>set(k,e.target.value)}/>}</label>)}{err&&<div className="error wide">{err}</div>}<div className="actions wide"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button disabled={busy}>{busy?"Saving...":"Save Customer"}</button></div></form></div></div>}

function Customers({businessId,onCount}){const[list,setList]=useState([]),[q,setQ]=useState(""),[loading,setLoading]=useState(true),[modal,setModal]=useState(null),[err,setErr]=useState("");
async function load(){setLoading(true);const{data,error}=await supabase.from("customers").select("*").eq("business_id",businessId).order("created_at",{ascending:false});if(error)setErr(error.message);setList(data||[]);onCount(data?.length||0);setLoading(false)}
useEffect(()=>{if(businessId)load()},[businessId]);
async function del(c){if(!confirm(`Delete ${c.name}?`))return;const{error}=await supabase.from("customers").delete().eq("id",c.id);if(error)setErr(error.message);else load()}
const filtered=useMemo(()=>{let x=q.toLowerCase().trim();return x?list.filter(c=>[c.name,c.phone,c.email,c.city,c.gst_number].some(v=>String(v||"").toLowerCase().includes(x))):list},[list,q]);
return <div className="page"><div className="heading"><div><small>CUSTOMER MANAGEMENT</small><h1>Customers</h1><p>Manage Neelkanth Stones customer records.</p></div><button onClick={()=>setModal("new")}><Plus/> Add Customer</button></div><section className="panel"><div className="toolbar"><div className="search"><Search/><input placeholder="Search name, phone, city or GST..." value={q} onChange={e=>setQ(e.target.value)}/></div><span>{filtered.length} customer{filtered.length!==1?"s":""}</span></div>{err&&<div className="error">{err}</div>}{loading?<div className="empty">Loading customers...</div>:filtered.length===0?<div className="empty"><Users/><strong>{q?"No matching customers":"No customers yet"}</strong>{!q&&<button className="secondary" onClick={()=>setModal("new")}><Plus/> Add Customer</button>}</div>:<div className="table"><table><thead><tr><th>Customer</th><th>Phone</th><th>City</th><th>GST</th><th></th></tr></thead><tbody>{filtered.map(c=><tr key={c.id}><td><strong>{c.name}</strong><small>{c.email||"No email"}</small></td><td>{c.phone||"—"}</td><td>{c.city||"—"}</td><td>{c.gst_number||"—"}</td><td><button className="icon" onClick={()=>setModal(c)}><Pencil/></button><button className="icon danger" onClick={()=>del(c)}><Trash2/></button></td></tr>)}</tbody></table></div>}</section>{modal&&<CustomerModal item={modal==="new"?null:modal} businessId={businessId} onClose={()=>setModal(null)} onDone={()=>{setModal(null);load()}}/>}</div>}

function App(){const[session,setSession]=useState(null),[business,setBusiness]=useState(null),[profile,setProfile]=useState(null),[page,setPage]=useState("dashboard"),[count,setCount]=useState(0),[mobile,setMobile]=useState(false),[loading,setLoading]=useState(true);
async function account(uid){const{data:p}=await supabase.from("profiles").select("*").eq("id",uid).maybeSingle();const{data:m}=await supabase.from("business_members").select("business_id,role,businesses(*)").eq("user_id",uid).eq("role","owner").maybeSingle();setProfile(p);setBusiness(m?.businesses||null);if(m?.business_id){const{count}=await supabase.from("customers").select("id",{count:"exact",head:true}).eq("business_id",m.business_id);setCount(count||0)}}
useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);if(data.session)account(data.session.user.id);setLoading(false)});const{data:l}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);if(s)account(s.user.id)});return()=>l.subscription.unsubscribe()},[]);
if(loading)return <div className="empty">Loading...</div>;if(!session)return <Login/>;const current=nav.find(x=>x[0]===page)||nav[0],Icon=current[2];
return <div className="app"><aside className={mobile?"side open":"side"}><div className="brand"><div className="logo">NS</div><b>Neelkanth</b><button className="icon mobile" onClick={()=>setMobile(false)}><X/></button></div><nav>{nav.map(([id,label,I])=><button className={page===id?"active":""} onClick={()=>{setPage(id);setMobile(false)}}><I/>{label}</button>)}</nav><div className="user">{profile?.full_name||"Owner"}<small>{session.user.email}</small><button onClick={()=>supabase.auth.signOut()}><LogOut/> Logout</button></div></aside><main><header><button className="icon mobile-menu" onClick={()=>setMobile(true)}><Menu/></button><Icon/>{current[1]}<span>{business?.name||"Neelkanth Stones"}</span></header>{page==="customers"?<Customers businessId={business?.id} onCount={setCount}/>:<div className="page"><div className="heading"><div><small>MODULE</small><h1>{current[1]}</h1><p>{current[1]==="Dashboard"?`Customers: ${count}`:"This module will be built next."}</p></div><button><Plus/> Add New</button></div><section className="panel empty"><Icon/><strong>{current[1]}</strong><p>Application foundation is ready.</p></section></div>}</main></div>}
export default App;
